### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Consulate'

### ISSUE THREAD

**Issue by gdhbashton** [gmr/consulate#17]
Hi, I installed 0.3.0 with `pip install https://github.com/gmr/consulate/archive/master.zip` on CentOS 7 / Python 2.7.5 - the CLI tool launches OK after install simplejson  / requests, but I am getting the error in $title

```
[root@ip-172-18-22-87 stub]# consul members
Node               Address             Status  Type    Build  Protocol
ip-172-18-22-87    172.18.22.87:8301   alive   client  0.4.1  2
bastion-i535bffb5  172.18.20.199:8301  alive   server  0.4.1  2
jenkins-ifa37e51d  172.18.22.165:8301  alive   client  0.4.1  2
bastion-i5d9840b9  172.18.21.36:8301   alive   server  0.4.1  2
bastion-idc50853b  172.18.19.30:8301   alive   server  0.4.1  2
```

```
[root@ip-172-18-22-87 stub]# consulate -h
usage: consulate [-h] [--api-host API_HOST] [--api-port API_PORT]
                 [--datacenter DATACENTER] [--token TOKEN]
                 {register,kv} ...

CLI utilities for Consul

optional arguments:
  -h, --help            show this help message and exit
  --api-host API_HOST   The consul host to connect on
  --api-port API_PORT   The consul API port to connect to
  --datacenter DATACENTER
                        The datacenter to specify for the connection
  --token TOKEN         ACL token

Commands:
  {register,kv}
    register            Register a service for this node
    kv                  Key/Value Database Utilities
```

```
[root@ip-172-18-22-87 stub]# consulate kv set mykey 123
Traceback (most recent call last):
  File "/bin/consulate", line 9, in <module>
    load_entry_point('consulate==0.3.0', 'console_scripts', 'consulate')()
  File "/usr/lib/python2.7/site-packages/consulate/cli.py", line 75, in main
    session = api.Consulate(args.api_host, args.api_port, args.datacenter,
AttributeError: 'module' object has no attribute 'Consulate'

```

Any help would be appreciated :)

Cheers,
Gavin.

**Comment by sielaq** [comment]
https://github.com/gmr/consulate/pull/18  fast fix
