### ISSUE TITLE
Importing consulate fails on CentOS 7

### ISSUE THREAD

**Issue by telmich** [gmr/consulate#24]
Installing it & trying to import results in:

    [10:56:04] vmhost1-cluster1:~# pip install consulate
    Downloading/unpacking consulate
      Downloading consulate-0.2.0.tar.gz
      Running setup.py (path:/tmp/pip-build-UdHBo_/consulate/setup.py) egg_info for package consulate
        
    Downloading/unpacking requests (from consulate)
      Downloading requests-2.5.3-py2.py3-none-any.whl (468kB): 468kB downloaded
    Installing collected packages: consulate, requests
      Running setup.py install for consulate
        
        Installing consulate script to /usr/bin
    Successfully installed consulate requests
    Cleaning up...
    [10:56:40] vmhost1-cluster1:~# python
    Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import consulate
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/consulate/__init__.py", line 7, in <module>
        from consulate.api import Consulate
      File "/usr/lib/python2.7/site-packages/consulate/api.py", line 10, in <module>
        from consulate import adapters
      File "/usr/lib/python2.7/site-packages/consulate/adapters.py", line 59, in <module>
        class TornadoRequest(Request):
      File "/usr/lib/python2.7/site-packages/consulate/adapters.py", line 66, in TornadoRequest
        @gen.coroutine
    AttributeError: 'NoneType' object has no attribute 'coroutine'
    >>> 
    [10:57:21] vmhost1-cluster1:~# cat /etc/redhat-release 
    CentOS Linux release 7.0.1406 (Core) 
    [10:57:31] vmhost1-cluster1:~# python --version
    Python 2.7.5
    [10:57:43] vmhost1-cluster1:~#

**Comment by sielaq** [comment]
Hi,
``pip install tornado``
tornado lib is needed

**Comment by gmr** [comment]
This should be resolved in the latest version (0.3.0) and does not require tornado to be installed.
