### ISSUE TITLE
Can't use catalog.register

### ISSUE THREAD

**Issue by rvrignaud** [gmr/consulate#49]
Hello,

It seems we can't use catalog.register in 0.5.x. It's working in 0.4.0 but with
```
consul.catalog.register(hostname,address)
```
I get the following stack trace : 
```
Traceback (most recent call last):
  File "./consul-register", line 84, in <module>
    register(consul, args)
  File "./consul-register", line 66, in register
    consul.catalog.register(hostname,address)
  File "/home/rvrignaud/.virtualenvs/consul-register/lib/python2.7/site-packages/consulate/api/catalog.py", line 95, in register
    return self._adapter.put(['register'], None, payload)
  File "/home/rvrignaud/.virtualenvs/consul-register/lib/python2.7/site-packages/consulate/adapters.py", line 39, in inner
    return fun(*args, **kwargs)
TypeError: put() takes at most 3 arguments (4 given)
```

Am I doing something wrong?

**Comment by pquentin** [comment]
After investigating a bit with @rvrignaud, it looks like the 07ddb59 refactor changed `result = self._adapter.put(self._build_uri(['register']), payload)` to `return self._put_no_response_body(['register'], None, payload)`. So, that's an additional `None` argument. But `consulate.adapters.Request.put` did not change, which explains the error. 

Thoughts?

**Comment by gmr** [comment]
Thanks for looking into it, I should have a fix shortly.

**Comment by gmr** [comment]
0.6.0 will include this fix.
