### ISSUE TITLE
pkg_resources.DistributionNotFound: argparse on latest rc 7

### ISSUE THREAD

**Issue by shakisha** [gmr/consulate#99]
i'm trying to backup and restore the consul kv consul-alerts configuration by running the command:

````
consulate kv backup consul-alerts/config -f consul-alerts-config.json
````
but it will throw me this error
````
consulate: error: unrecognized arguments: consul-alerts/config
````

Maybe a new different version of consulate not allowing me to specify the kv to backup?

**Comment by shakisha** [comment]
ok, i have seen that this issue is because i was using stable version of consulate (6) instead of release candidate (7).

But now, when using 
````
pip install --upgrade git+https://github.com/gmr/consulate.git
````
i have got this error when running consulate:
````
Traceback (most recent call last):
  File "/usr/bin/consulate", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: argparse
````

latest stable version was not giving me this error.

**Comment by shakisha** [comment]
Now i have run 
````
yum -y reinstall python-argparse python-pip 
````

and the error changed to 

````
Traceback (most recent call last):
  File "/usr/bin/consulate", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.0.0,<3.0.0
````

**Comment by shakisha** [comment]
Of course, 

````
pip list | grep "requests"
````
gives me 
````
requests (2.12.4)
````

**Comment by shakisha** [comment]
trouble fixed running these commands:

    pip install --upgrade git+https://github.com/gmr/consulate.git
    easy_install --upgrade requests
    yum -y reinstall python-argparse
